import Head from "next/head";
import { BsFillMoonStarsFill } from 'react-icons/bs'



export default function Home() {


  return (
    <div>
      <Head>
        <title>Evgeny Zbirun Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className=" bg-yellow-200 min-h-screen">
          <nav className="py-10 mb-14 flex justify-between">
            <h1 className="text-xl">developed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-600 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  );
}
